### ISSUE TITLE
🐛 CI failure: test_paged_stashing.py::TestPagedStashing::test_forward_backward_4_layers

### ISSUE THREAD

**Issue by ko3n1g** [NVIDIA/Megatron-LM#4339]
**Describe the bug**

CI test `tests/unit_tests/transformer/moe/test_paged_stashing.py::TestPagedStashing::test_forward_backward_4_layers` failed in job [tests/unit_tests/transformer/moe/**/*.py - latest](https://github.com/NVIDIA/Megatron-LM/actions/runs/24510353170/job/71641206557).
Tag the [@mcore-oncall](https://github.com/orgs/NVIDIA/teams/mcore-oncall) to get oncall's attention to this issue.

**Failing run**

| Field | Value |
|-------|-------|
| PR    | [#4332: build: bump TransformerEngine to release_v2.14 (dev)](https://github.com/NVIDIA/Megatron-LM/pull/4332) |
| Run   | [24510353170](https://github.com/NVIDIA/Megatron-LM/actions/runs/24510353170) |
| Job   | [71641206557](https://github.com/NVIDIA/Megatron-LM/actions/runs/24510353170/job/71641206557) |

**Error**

```
tests/unit_tests/transformer/moe/test_paged_stashing.py::TestPagedStashing::test_forward_backward_4_layers

  File "megatron/core/transformer/moe/experts.py", line 730, in TEGroupedMLP.__init__
        if self.config.use_transformer_engine_op_fuser:
            assert (
>               self._is_fused_impl_supported()
            ), "Fused GroupedMLP is not supported for this configuration."
E           AssertionError: Fused GroupedMLP is not supported for this configuration.

megatron/core/transformer/moe/experts.py:730: AssertionError
```

The test constructs a `MoEModelTestContainer` with `use_transformer_engine_op_fuser=True` and `moe_paged_stash=True`. The `TEGroupedMLP.__init__` guard at `experts.py:730` rejects this combination because `_is_fused_impl_supported()` returns `False`, indicating the fused TE op fuser path does not support paged stashing.

**Steps/Code to reproduce bug**

Re-run the failing CI job linked above, or locally inside the dev container:

```bash
pytest tests/unit_tests/transformer/moe/test_paged_stashing.py::TestPagedStashing::test_forward_backward_4_layers
```

**Additional context**

Triaged automatically via `/triage-issue`.

**Comment by ko3n1g** [comment]
Likely stale duplicate of #4935, fixed by #4978.

Both issues stem from the same root cause: the `TestPagedStashing` and `TestPagedStashingOverBudget` classes configure `fp8_recipe='mxfp8'`, but MXFP8 in TE requires compute capability >= 10.0 (Blackwell). On H100/A100 CI runners, the test either:

- (this issue, TE 2.14 path) — trips the `_is_fused_impl_supported()` assertion at `experts.py:730` because the fused-op + MXFP8 combo can't be constructed on SM90, or
- (#4935) — trips `'functools.partial' object has no attribute 'submodules'` at `test_paged_stashing.py:139` once the spec layout changed.

PR #4978 adds a class-level `@pytest.mark.skipif(not _is_mxfp8_supported())` (requires SM>=10) to both test classes, which short-circuits the test on H100/A100 before either error path is reached. It also removes the `flaky_in_dev` masking that was hiding the missing hardware gate.

Will close automatically once #4978 merges (linked via `Closes #4935`). Re-open if a different failure mode shows up on Blackwell after PR #4978 lands.

cc @nanz-nv
